---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockscout-user-ops-indexer.fullname" . }}-env
  labels:
    {{- include "blockscout-user-ops-indexer.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.userOpsIndexer.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

