---

quorumFlags:
  removeGenesisOnDelete: true

# the raw Genesis config
# rawGenesisConfig.blockchain.nodes set the number of validators/signers
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm:
        consensus: qbft
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    gasLimit: '0xf7b760' 
    difficulty: '0x1'
    coinbase: '0x0000000000000000000000000000000000000000'
    maxCodeSize: 64000  # 64 KB
    txnSizeLimit: 64000  # 64 KB
  blockchain:
    nodes:
      generate: true
      count: 4
    accountPassword: 'password'


image:
  repository: docker.io/consensys
  name: quorum-k8s-hooks
  tag: qgt-0.2.20 
  pullPolicy: IfNotPresent
