---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockscout-sig-provider.fullname" . }}
  labels:
    {{- include "blockscout-sig-provider.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sigProvider.replicaCount }}
  selector:
    matchLabels:
      {{- include "blockscout-sig-provider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blockscout-sig-provider.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: sig-provider
        image: "{{ .Values.sigProvider.image.repository }}/{{ .Values.sigProvider.image.name }}:{{ .Values.sigProvider.image.tag }}"
        imagePullPolicy: {{ .Values.sigProvider.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.sigProvider.service.targetPort }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "blockscout-sig-provider.fullname" . }}-env
        resources:
          {{- toYaml .Values.sigProvider.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.sigProvider.livenessProbe.path }}
            port: http
            scheme: HTTP
          {{- with .Values.sigProvider.livenessProbe.params }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        readinessProbe:
          httpGet:
            path: {{ .Values.sigProvider.readinessProbe.path }}
            port: http
            scheme: HTTP
          {{- with .Values.sigProvider.readinessProbe.params }}
          {{- toYaml . | nindent 10 }}
          {{- end }}

