---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockscout-eth-bytecode-db.fullname" . }}-env
  labels:
    {{- include "blockscout-eth-bytecode-db.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.ethBytecodeDb.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

