---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu-node.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm    
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  ports:
    - name: json-rpc
      port: {{ .Values.node.besu.rpc.port }}
      targetPort: json-rpc
      protocol: TCP
    - name: ws
      port: {{ .Values.node.besu.ws.port }}
      targetPort: ws
      protocol: TCP
    - name: graphql
      port: {{ .Values.node.besu.graphql.port }}
      targetPort: graphql
      protocol: TCP
    - name: rlpx
      port: {{ .Values.node.besu.p2p.port }}
      targetPort: rlpx
      protocol: TCP
    - name: discovery
      port: {{ .Values.node.besu.p2p.port }}
      targetPort: discovery
      protocol: UDP
    - name: metrics
      port: {{ .Values.node.besu.metrics.port }}
      targetPort: metrics
      protocol: TCP
      
{{- if .Values.quorumFlags.privacy }}          
    - name: tessera
      port: {{ .Values.node.tessera.port }}
      targetPort: tessera
      protocol: TCP
    - name: tessera-tp
      port: {{ .Values.node.tessera.tpport }}
      targetPort: tessera-tp
      protocol: TCP
    - name: tessera-q2t
      port: {{ .Values.node.tessera.q2tport }}
      targetPort: tessera-q2t
      protocol: TCP
{{- end }}

