{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.tls.certificate .Values.ingress.tls.privateKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "besu-node.fullname" . }}-tls
  labels:
    app.kubernetes.io/name: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/component: ingress-tls
    app.kubernetes.io/part-of: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.certificate | b64enc }}
  tls.key: {{ .Values.ingress.tls.privateKey | b64enc }}
{{- end }}

