---

quorumFlags:
  privacy: false
  removeKeysOnDelete: true
  isBootnode: true    # Besu only, set this to true if this node is a bootnode
  usesBootnodes: true # Besu only, set this to true if the network you are connecting to use a bootnode/s that are deployed in the cluster 

node:
  besu:
    envBesuOpts: ""  
    metrics:
      serviceMonitorEnabled: true
    resources:
      cpuLimit: 1
      cpuRequest: 0.5
      memLimit: "2G"
      memRequest: "1G"
    account:
      password: 'password'
    customLabels:
      nodeType: bootnode

