---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockscout.fullname" . }}-env
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  DATABASE_URL: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ include "blockscout.fullname" . }}-db:5432/{{ .Values.db.database }}"

