---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout.fullname" . }}-db
  labels:
    {{- include "blockscout.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.db.password | b64enc }}

