---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "blockscout.fullname" . }}-db-storage
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
    {{- include "blockscout.labels" . | nindent 4 }}
spec:
  persistentVolumeReclaimPolicy: {{ .Values.db.storage.reclaimPolicy }}
  storageClassName: {{ include "blockscout.fullname" . }}-db-storage
  capacity:
    storage: "{{ .Values.db.storage.size }}"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/{{ include "blockscout.fullname" . }}-db"

