apiVersion: v2
name: blockscout-user-ops-indexer
description: Blockscout user-ops-indexer service
type: application
version: 0.1.0
appVersion: latest
keywords:
  - blockscout
  - user-ops-indexer
  - explorer
  - ethereum
home: https://github.com/blockscout/blockscout
maintainers:
  - name: Blockscout Team

