---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockscout-visualizer.fullname" . }}-env
  labels:
    {{- include "blockscout-visualizer.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.visualizer.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

