---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout-visualizer.fullname" . }}
  labels:
    {{- include "blockscout-visualizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.visualizer.service.type }}
  ports:
    - port: {{ .Values.visualizer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "blockscout-visualizer.selectorLabels" . | nindent 4 }}

