---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockscout-proxy-verifier.fullname" . }}-env
  labels:
    {{- include "blockscout-proxy-verifier.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.proxyVerifier.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

