---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout-proxy-verifier.fullname" . }}
  labels:
    {{- include "blockscout-proxy-verifier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxyVerifier.service.type }}
  ports:
    - port: {{ .Values.proxyVerifier.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.proxyVerifier.metrics.enabled }}
    - port: {{ .Values.proxyVerifier.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "blockscout-proxy-verifier.selectorLabels" . | nindent 4 }}

