---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockscout-stats.fullname" . }}-env
  labels:
    {{- include "blockscout-stats.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.stats.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  STATS__DB_URL: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ include "blockscout-stats.fullname" . }}-db:5432/{{ .Values.db.database }}"


