---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout-stats.fullname" . }}
  labels:
    {{- include "blockscout-stats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.stats.service.type }}
  ports:
    - port: {{ .Values.stats.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.stats.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "blockscout-stats.selectorLabels" . | nindent 4 }}

